# Generated by Django 5.1.2 on 2025-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customusuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
