# Generated by Django 5.1.2 on 2024-11-15 16:38

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animal_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raça',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Raça')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='fotos_animais/', variations={'thumb': (1080, 1080, True)}, verbose_name='Fotos'),
        ),
    ]
