# Generated by Django 5.1.2 on 2025-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customusuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Membro da equipe'),
        ),
    ]
