# Generated by Django 5.1.2 on 2024-11-16 17:11

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_raça_alter_animal_descricao_alter_animal_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('telefone', models.CharField(default=0, max_length=15)),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='fotos_voluntarios/', variations={'thumb': (1080, 1080, True)}, verbose_name='Fotos')),
                ('linkedin', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
        migrations.RenameModel(
            old_name='Raça',
            new_name='Raca',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Doguinho', 'verbose_name_plural': 'Doguinhos'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
