# Generated by Django 5.1.2 on 2025-01-10 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customusuario_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membro da equipe'),
        ),
    ]
