# Generated by Django 5.0.6 on 2025-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customusuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='local',
            field=models.CharField(default='', max_length=100),
        ),
    ]
